dataset:
  data_dir: /data/visdial/

  image_features_train_h5: features_faster_rcnn_x101_train.h5
  image_features_val_h5: features_faster_rcnn_x101_val.h5
  image_features_test_h5: features_faster_rcnn_x101_test.h5

  train_json: visdial_1.0_train.json
  val_json: visdial_1.0_val.json
  test_json: visdial_1.0_test.json

  train_dense_json: visdial_1.0_train_dense_annotations.json
  val_dense_json: visdial_1.0_val_dense_annotations.json

  val_json_vispro: visdial_1.0_val_vispro.json
  val_json_visdialconv: visdial_1.0_val_crowdsourced.json

  val_dense_json_vispro: visdial_1.0_val_dense_annotations_vispro.json
  val_dense_json_visdialconv: visdial_1.0_val_dense_annotations_crowdsourced.json

  word_counts_json: visdial_1.0_word_counts_train.json
  glove_npy: glove.npy